encryptionKey = "${WALLET_ENCRYPTION_KEY}" // 16 chars, generated per deployment
signKey = "${WALLET_SIGN_KEY}" // 16 chars, generated per deployment

# Available Signing Algorithms are: RS256 or HS256.
# If HS256, then provide the 256+ bit key in the tokenKey field. If RS256, then provide the private key in JWK format in the tokenKey field.
;tokenKey = "<a - longer 256+ bit key or rsa private key in jwk format- here>" // at least 256 bit (32 chars)

# Examples:
; tokenKey = "hjklwcptiniwjkdwwkigreumcayoyiso"
tokenKey = "${WALLET_TOKEN_KEY}" // 32+ chars, generated per deployment
audTokenClaim = "https://${WALLET_HOST}"
issTokenClaim = "https://${WALLET_HOST}"
tokenLifetime = "30"//days
