services:
  ocean-market:
    build:
      context: .
      dockerfile: Dockerfile
    image: purpleshadows/market-empower-x:latest
    container_name: ocean-market
    ports:
      - '8008:0802'
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
