services:
  ocean-market:
    build:
      context: .
      dockerfile: Dockerfile
    image: personal-data-market:local
    container_name: ocean-market
    ports:
      - '8008:8008'
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
