#!/bin/sh
set -eu

node - <<'NODE'
const fs = require('fs')

const config = {
  NEXT_PUBLIC_ENCRYPT_ASSET: process.env.NEXT_PUBLIC_ENCRYPT_ASSET,
  NEXT_PUBLIC_SSI_WALLET_API: process.env.NEXT_PUBLIC_SSI_WALLET_API,
  NEXT_PUBLIC_METADATACACHE_URI: process.env.NEXT_PUBLIC_METADATACACHE_URI,
  NEXT_PUBLIC_PROVIDER_URL: process.env.NEXT_PUBLIC_PROVIDER_URL,
  NEXT_PUBLIC_IPFS_UNPIN_FILES: process.env.NEXT_PUBLIC_IPFS_UNPIN_FILES,
  NEXT_PUBLIC_NODE_URI: process.env.NEXT_PUBLIC_NODE_URI,
  NEXT_PUBLIC_IPFS_GATEWAY: process.env.NEXT_PUBLIC_IPFS_GATEWAY,
  NEXT_PUBLIC_SSI_POLICY_SERVER: process.env.NEXT_PUBLIC_SSI_POLICY_SERVER,
  NEXT_PUBLIC_SSI_DEFAULT_POLICIES_URL:
    process.env.NEXT_PUBLIC_SSI_DEFAULT_POLICIES_URL,
  NEXT_PUBLIC_OPA_SERVER_URL: process.env.NEXT_PUBLIC_OPA_SERVER_URL,
  NEXT_PUBLIC_SSI_ENABLED: process.env.NEXT_PUBLIC_SSI_ENABLED,
  NEXT_PUBLIC_HIDE_ONBOARDING_MODULE_BY_DEFAULT:
    process.env.NEXT_PUBLIC_HIDE_ONBOARDING_MODULE_BY_DEFAULT,
  NEXT_PUBLIC_NODE_URI_INDEXED: process.env.NEXT_PUBLIC_NODE_URI_INDEXED,
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID,
  NEXT_PUBLIC_CONSUME_MARKET_FEE: process.env.NEXT_PUBLIC_CONSUME_MARKET_FEE,
  NEXT_PUBLIC_CONSUME_MARKET_ORDER_FEE_MAP:
    process.env.NEXT_PUBLIC_CONSUME_MARKET_ORDER_FEE_MAP,
  NEXT_PUBLIC_FIXED_RATE_EXCHANGE_ADDRESS:
    process.env.NEXT_PUBLIC_FIXED_RATE_EXCHANGE_ADDRESS,
  NEXT_PUBLIC_DISPENSER_ADDRESS: process.env.NEXT_PUBLIC_DISPENSER_ADDRESS,
  NEXT_PUBLIC_NFT_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_NFT_FACTORY_ADDRESS,
  NEXT_PUBLIC_ROUTER_FACTORY_ADDRESS:
    process.env.NEXT_PUBLIC_ROUTER_FACTORY_ADDRESS,
  NEXT_PUBLIC_ACCESS_LIST_FACTORY_ADDRESS:
    process.env.NEXT_PUBLIC_ACCESS_LIST_FACTORY_ADDRESS,
  NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION:
    process.env.NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION,
  NEXT_PUBLIC_NODE_URI_MAP: process.env.NEXT_PUBLIC_NODE_URI_MAP,
  NEXT_PUBLIC_MARKET_FEE_ADDRESS: process.env.NEXT_PUBLIC_MARKET_FEE_ADDRESS,
  NEXT_PUBLIC_ALLOWED_ERC20_ADDRESSES:
    process.env.NEXT_PUBLIC_ALLOWED_ERC20_ADDRESSES,
  NEXT_PUBLIC_DATASPACE: process.env.NEXT_PUBLIC_DATASPACE,
  NEXT_PUBLIC_AUTH_ENABLED: process.env.NEXT_PUBLIC_AUTH_ENABLED,
  NEXT_PUBLIC_AUTH_PROVIDER: process.env.NEXT_PUBLIC_AUTH_PROVIDER,
  NEXT_PUBLIC_OIDC_TOKEN_URL: process.env.NEXT_PUBLIC_OIDC_TOKEN_URL,
  NEXT_PUBLIC_OIDC_ISSUER: process.env.NEXT_PUBLIC_OIDC_ISSUER,
  NEXT_PUBLIC_OIDC_CLIENT_ID: process.env.NEXT_PUBLIC_OIDC_CLIENT_ID,
  NEXT_PUBLIC_OIDC_REDIRECT_URI: process.env.NEXT_PUBLIC_OIDC_REDIRECT_URI,
  NEXT_PUBLIC_MAX_LICENSE_FILE_SIZE_KB: process.env.NEXT_PUBLIC_MAX_LICENSE_FILE_SIZE_KB
}

fs.writeFileSync(
  '/app/public/runtime-config.js',
  `window.__RUNTIME_CONFIG__ = ${JSON.stringify(config)};\n`
)
NODE

exec "$@"
